### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by yangm97** [group-butler/GroupButler#220]
Instead of sending the log to Telegram, output JSON formatted log to stdout, collect and digest the logs using some other tool like logstash or graylog.

https://www.loggly.com/blog/why-json-is-the-best-application-log-format-and-how-to-switch/

https://journal.paul.querna.org/articles/2011/12/26/log-for-machines-in-json/

http://dev.splunk.com/view/logging-best-practices/SP-CAAAFCK

https://www.graylog.org

https://docs.docker.com/engine/admin/logging/overview/#supported-logging-drivers

**Comment by NotAFile** [comment]
I personally value at least having an option of human-readable logs a lot.

**Comment by yangm97** [comment]
So what about this:

Make a customisable log function/module with levels mimicking ngx.log ones. In config you could set where and how you want the logs delivered: stdout (either json or human), telegram, prometheus, etc.

**Comment by NotAFile** [comment]
Yeah, most coventional logging libraries allow you to plug long handlers that do different things with the logs, e.g. print them, email them, transmit them.

What twisted does, which I really really like is the following:

    log.error("new group {groupname}, {membercount}", name="whatever", membercount=34)

That way, you can have both human and machine readable logs at the same time. You can set up different handlers for these messages then.

More generally, I think it's a mistake to take things that make sense on a large e.g. facebook or netflix scale and try to emulate it "just because". JSON logs, ELK stack etc. probably doesn't make sense for most GB deployments, the official one even, where there is a single server, single process, and a "grep" command can search it in less than a millisecond.

**Comment by yangm97** [comment]
I think dendrite has some kind of middle ground logging too, somewhat like this:

```
time="2018-06-23T16:15:41.788287481Z" level=warning msg="Didn't call Close on UserStreamListener" req.id=kQrtSRo4EDSm req.method=GET req.path=/_matrix/client/r0/sync
```

(Of course we don’t need millisecond precision but you get the idea)

But yeah, different log handlers. Telegram log handler could wrap some nice markdown around while stdout handler could look like that.

**Comment by yangm97** [comment]
Since the issue was too broad and "logging" has "improved", I'm going to close this.
