### ISSUE TITLE
Old update skipped slows down bot to a halt

### ISSUE THREAD

**Issue by seth-rah** [group-butler/GroupButler#293]
Us

When the bot starts posting "old update skipped, it becomes completely unresponsive until the sequence stops. No commands are accepted during that.

![image](https://user-images.githubusercontent.com/2222634/38348570-ec9e4c22-38a2-11e8-8a9d-cdc47a1d15b3.png)

I don't know why the bot is putting old update skipped in the logs either, but it happens really often.

What happened in the image above is between 21:47 and 21:48, there was some work the bot was required to do however it ignored all the requests.

### Expected behaviour

The bot should continue as normal while this behavior is seen.

### Actual behaviour

The bot does not accept any commands and cannot operate.

**Operating system:** 

Ubuntu

Bot version (Latest pull from git)

Environment: Docker

**Comment by seth-rah** [comment]
Another instance of this occurring

![image](https://user-images.githubusercontent.com/2222634/38350982-eb869c62-38ad-11e8-82e9-2f71b0f99fd4.png)

**Comment by bhsgoclub** [comment]
I’ve been looking into this too. Home machine? Or third party container? And if container where from? I have a couple hunches.

**Comment by seth-rah** [comment]
This is being hosted on a digital ocean droplet for ubuntu.

**Comment by Qwerty-Space** [comment]
You can remove the update time, or make it longer than 7 seconds.  [Here](https://github.com/RememberTheAir/GroupButler/blob/master/lua/main.lua#L68)

**Comment by seth-rah** [comment]
Think I will do that by exec'ing into the container

If I can ask how negative would the effects be if I changed it to like 30 - 60 seconds?

Seeing as the bot does stop for that amount of time, hoping to give it that grace period, but I am not completely sure what the impact would be for multiple messages.

**Comment by Qwerty-Space** [comment]
Shouldn't be a negative effect.

**Comment by seth-rah** [comment]
Managed to swipe the logs of the bot

I had other instances that were about 5 seconds out it seems, so I plan on changing my own bot to a 30 second grace rather than 7, as I see my OS time and container time don't match each other.



```
2018-04-08T17:54:00.043109160Z Old update skipped ||| OS TIME & DATE =  1523210040 ||| OS TIME & DATE - 7 1523210033 ||| MSGDATE =  1523210032 <-- Must be larger than -7 value
```

**Comment by AncalagonTheBlack** [comment]
I have the same problem but with the non docker version. Everything works fine but after a while the bot just keeps stopping his work

**Comment by yangm97** [comment]
This issue is kind hard to tackle. I turned the `old_update` magic number into a configurable option (on webhooks branch, could cherry pick that) because I was having issues with the docker vm time drifting away, but I’m not happy with that still.

I thought of moving the old_update check out of the main loop to plugins which are time sensitive, but that would bring back the issue of the bot spamming back users who sent commands while it was down for hours, so maybe a more generous old_update check on main + sensible check for sensible plugins? So while things like anti flood could fail, the bot would still be up.

Any ideas, besides treating bug as “not our fault”?

**Comment by NotAFile** [comment]
@yangm97 it would make more sense for anything that relied on any kind of date or time computations to access the thing itself

**Comment by yangm97** [comment]
I think all causes for this issues have been fixed by now

1. old_update is now configurable
2. timezone issues seem to have been fixed
3. webhooks, which handles old and new updates __simultaneouly__ (since telegram sends updates out of order) is faster than polling mode at skipping old updates

So I'm closing it. As for the issue of not having a global old_update check, that probably belongs to #417.

**Comment by seth-rah** [comment]
Is old_update configured as an environment variable in the docker-compose file?

**Comment by yangm97** [comment]
@seth-rah Yes. It’s GB_OLD_UPDATE

**Comment by seth-rah** [comment]
Thanks
